a=2
b=3
print(' Operators in python')

print('Arithmetic operators')
print('+ operator performs addition of variables')
print('a+b=',a+b)
print('- operator performs subtraction of variables')
print('a-b=',a-b)
print('* operator performs multiplication of variables')
print('a*b=',a*b)
print('/ operator performs division of variables')
print('a/b=',a/b)
print('// operator is floor division operator')
print('a//b=',a//b)
print('** operator is power operator ')
print('a**b=',a**b)
print('% operator is modulous operator')
print('a%b=',a%b)

print('relational operators')
print("a<b for a =2 and b=3 is")
print(a<b)
print("a>b for a =2 and b=3 is")
print(a>b)
print("a<=b for a =2 and b=3 is")
print(a<=b)
print("a>=b for a =2 and b=3 is")
print(a>=b)
print("a==b for a =2 and b=3 is")
print(a==b)

print('Logical operator')
print('and operator')
print(a and b )
print('or operator')
print(a or b )
print('not operator')
print(  not b )

print('bitwise operator')
print('bitwise & operator')
print(a&b)
print('bitwise | operator')
print(a|b)
print('bitwise << operator')
print(a<<b)
print('bitwise >> operator')
print(a>>b)
print('bitwise ~ operator')
print(~b)
print('bitwise ^ operator')
print(a^b)